config/routes.rb
Rails.application.routes.draw do
  resources :order_details
  resources :orders
  resources :customers
  resources :foods
  resources :categories
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get '/reports', to: "reports#index"
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :category
  validates :name, presence: true, uniqueness: true
  validates :description, presence: true, length: { maximum: 150 }
  validates :price, presence:true, numericality: true
  validates_numericality_of :price, :greater_than => 0.01
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: %i[ show edit update destroy ]

  # GET /foods or /foods.json
  def index
    @foods = Food.all
  end

  # GET /foods/1 or /foods/1.json
  def show
  end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit
  end

  # POST /foods or /foods.json
  def create
    @food = Food.new(food_params)

    respond_to do |format|
      if @food.save
        format.html { redirect_to food_url(@food), notice: "Food was successfully created." }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1 or /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to food_url(@food), notice: "Food was successfully updated." }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1 or /foods/1.json
  def destroy
    @food.destroy

    respond_to do |format|
      format.html { redirect_to foods_url, notice: "Food was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food
      @food = Food.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def food_params
      params.require(:food).permit(:name, :description, :price, :category_id)
    end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/_food.html.erb
<div id="<%= dom_id food %>">
  <p>
    <strong>Name:</strong>
    <%= food.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= food.description %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= food.price %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= food.category.name %>
  </p>

</div>

app/views/foods/_form.html.erb
<%= form_with(model: food) do |form| %>
  <% if food.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
        <% food.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.label :category_id, style: "display: block" %>
    <%= form.collection_select :category_id, Category.all, :id, :name, :include_blank => true %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/foods/edit.html.erb
<h1>Editing food</h1>

<%= render "form", food: @food %>

<br>

<div>
  <%= link_to "Show this food", @food %> |
  <%= link_to "Back to foods", foods_path %>
</div>

app/views/foods/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Foods</h1>

<div id="foods">
  <% @foods.each do |food| %>
    <%= render food %>
    <p>
      <%= link_to "Show this food", food %>
    </p>
  <% end %>
</div>

<%= link_to "New food", new_food_path %>

app/views/foods/new.html.erb
<h1>New food</h1>

<%= render "form", food: @food %>

<br>

<div>
  <%= link_to "Back to foods", foods_path %>
</div>

app/views/foods/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @food %>

<div>
  <%= link_to "Edit this food", edit_food_path(@food) %> |
  <%= link_to "Back to foods", foods_path %>

  <%= button_to "Destroy this food", @food, method: :delete %>
</div>